# Generated by Django 4.2.13 on 2024-06-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_post_avg_score_post_total_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="rate_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
