# Generated by Django 4.2.13 on 2024-06-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_post_std_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sum_of_squared_scores",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
